# Generated by Django 2.1.7 on 2021-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_description', models.CharField(max_length=300)),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
