# Generated by Django 2.1.7 on 2021-11-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_eventsdata_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsdata',
            name='event_time',
            field=models.TimeField(default='15:00'),
        ),
    ]
