# Generated by Django 2.0 on 2021-10-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alumniData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=8)),
                ('Birthdate', models.DateField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, max_length=120, null=True)),
                ('BatchYear', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='branchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='courseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='alumnidata',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Interface.branchData'),
        ),
        migrations.AddField(
            model_name='alumnidata',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Interface.courseData'),
        ),
        migrations.AddField(
            model_name='alumnidata',
            name='Email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
