# Generated by Django 3.2.8 on 2021-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidata',
            name='Profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
