# Generated by Django 2.1.7 on 2021-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_alter_alumnidata_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidata',
            name='Gender',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('male', 'MALE'), ('female', 'FEMALE')], default='unknown', max_length=8),
        ),
    ]
