# Generated by Django 2.1.7 on 2021-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0006_auto_20211124_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnidata',
            name='Phone_number',
            field=models.IntegerField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumnidata',
            name='Profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
