# Generated by Django 3.2.8 on 2021-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/default.jpg', null=True, upload_to='blog_images'),
        ),
    ]
